import { getCloudflareContext } from "@opennextjs/cloudflare";

/**
 * Branded fallback OG image, served at /og-default and referenced by
 * lib/metadata.ts's DEFAULT_OG_IMAGE. Pre-generated by the standalone
 * cnf-og-generator Worker (workers/og-generator) and stored in the
 * cnf-website-og-images R2 bucket — this route just reads it back out.
 * Previously generated on-the-fly here via next/og's ImageResponse, which
 * bundled a WASM image renderer into this Worker (~1MB gzip) — moving
 * generation out cuts that from the main site's bundle entirely.
 */
export async function GET() {
  const { env } = await getCloudflareContext({ async: true });
  const object = await env.OG_IMAGES_BUCKET.get("og-default.png");

  if (!object) {
    return new Response("Not found", { status: 404 });
  }

  return new Response(object.body as unknown as ReadableStream, {
    headers: {
      "Content-Type": "image/png",
      "Cache-Control": "public, max-age=3600",
    },
  });
}
