import { getCloudflareContext } from "@opennextjs/cloudflare";
import { client } from "@/sanity/lib/client";
import { MAJOR_EVENT_BY_SLUG_QUERY } from "@/sanity/lib/queries";
import { urlForImage } from "@/sanity/lib/image";
import type { MajorEvent } from "@/sanity/lib/types";

export const alt = "Criticals and Fumbles Event";
export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

/**
 * Per-event OG image. Real event photo (if set) is proxied straight from
 * Sanity's CDN; the branded text fallback is pre-generated by the
 * standalone cnf-og-generator Worker (webhook-triggered on publish) and
 * read back from the cnf-website-og-images R2 bucket here — not rendered
 * on-the-fly with next/og anymore (see app/og-default/route.tsx for why).
 */
export default async function Image({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const event = await client.fetch<MajorEvent | null>(MAJOR_EVENT_BY_SLUG_QUERY, {
    slug,
  });

  const photoUrl = urlForImage(event?.splashImage ?? event?.coverImage)
    ?.width(size.width)
    .height(size.height)
    .url();

  if (photoUrl) {
    const photoRes = await fetch(photoUrl);
    return new Response(photoRes.body, {
      headers: {
        "Content-Type": photoRes.headers.get("content-type") ?? "image/jpeg",
        "Cache-Control": "public, max-age=3600",
      },
    });
  }

  const { env } = await getCloudflareContext({ async: true });
  const object =
    (await env.OG_IMAGES_BUCKET.get(`events/${slug}.png`)) ??
    (await env.OG_IMAGES_BUCKET.get("og-default.png"));

  if (!object) {
    return new Response("Not found", { status: 404 });
  }

  return new Response(object.body as unknown as ReadableStream, {
    headers: {
      "Content-Type": "image/png",
      "Cache-Control": "public, max-age=3600",
    },
  });
}
